---
# File: user_group.yml - User and group settings

# Add group
- name: Add Consul group
  ansible.builtin.group:
    name: "{{ consul_group }}"
    state: present
  when:
    - consul_manage_group
    - not consul_install_from_repo

# Add user
- name: Add Consul user
  ansible.builtin.user:
    name: "{{ consul_user }}"
    comment: "Consul user"
    group: "{{ consul_group }}"
    system: true
  when:
    - consul_manage_user
    - not consul_install_from_repo
