---

- hosts: postgres_cluster
  vars:
    remove_postgres: false  # or 'true' to remove the database
    remove_consul: false  # or 'true' to remove the consul data
  become: true
  vars_files:
    - "vars/main-{{ environment }}.yml"
    - vars/{{ ansible_os_family }}.yml
  tasks:
    - name: Stop Patroni service
      service:
        name: patroni
        state: stopped
        enabled: false
    - name: Delete PostgreSQL database content
      file:
        path: "{{ postgresql_data_dir }}"
        state: absent
      when: remove_postgres|bool
    - name: Delete PgBackRest repository
      file:
        # path: pgbackrest_conf global repo1-path
        path: /var/lib/pgbackrest
        state: absent
      when: pgbackrest_install|bool
    - name: Stop Consul service
      service:
        name: consul
        state: stopped
        enabled: false
    - name: Delete Consul content
      file:
        path: "{{ consul_data_path }}"
        state: absent
      when: remove_consul|bool

- hosts: etcd_cluster
  vars:
    remove_etcd: false  # or 'true' to remove the database
  become: true
  vars_files:
    - "vars/main-{{ environment }}.yml"
  tasks:
    - name: Stop Etcd service
      service:
        name: etcd
        state: stopped
        enabled: false
    - name: Delete Etcd content
      file:
        path: "{{ etcd_data_dir }}/member"
        state: absent
      when: remove_etcd|bool

...
