---

# install wal-g package from repo
- block:
    - name: download "wal-g" binary
      get_url:
        url: '{{ item }}'
        dest: /tmp/
        timeout: 60
        validate_certs: no
      loop:
        - '{{ wal_g_package_repo }}'
      environment: '{{ proxy_env | default({}) }}'

    - name: extract "wal-g" into /tmp
      unarchive:
        src: '/tmp/{{ wal_g_package_repo | basename }}'
        dest: /tmp/
        remote_src: yes

    - name: copy "wal-g" binary files to /usr/local/bin/
      copy:
        src: "/tmp/wal-g"
        dest: /usr/local/bin/
        mode: u+x,g+x,o+x
        remote_src: yes
      loop:
        - wal-g

    - name: wal-g | create wal-g conf directory
      file:
        path: /etc/wal_g/envdir
        state: directory

  when: installation_method == "repo" and wal_g_package_repo | length > 0
  tags: wal_g_install

# install wal-g package from file
- block:
    - name: extract "wal-g" into /tmp
      unarchive:
        src: '{{ wal_g_package_file }}'
        dest: /tmp/

    - name: copy "wal-g" binary files to /usr/local/bin/
      copy:
        src: "/tmp/wal-g"
        dest: /usr/local/bin/
        mode: u+x,g+x,o+x
        remote_src: yes
      loop:
        - wal-g

    - name: wal-g | create wal-g conf directory
      file:
        path: /etc/wal_g/envdir
        state: directory

  when: installation_method == "file" and wal_g_package_file | length > 0
  tags: wal_g_install
