---
- name: Ensure firewalld is present.
  ansible.builtin.package:
    name: ufw
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Configure ufw rules.
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ firewall_allowed_tcp_ports }}"
