---
- name: Clean yum cache
  ansible.builtin.command: yum clean all
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == '7'

- name: Clean dnf cache
  ansible.builtin.command: dnf clean all
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version is version('8', '>=')

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_status
  until: apt_status is success
  delay: 5
  retries: 3
  when: ansible_os_family == "Debian"

- name: Update all system packages
  ansible.builtin.package:
    name: '*'
    state: latest
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  ignore_errors: true

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required
  changed_when: reboot_required.stat.exists
  when: ansible_os_family == "Debian"
  notify: "reboot host"

- name: Check if a reboot is required.
  ansible.builtin.command: needs-restarting -r
  register: reboot_required
  ignore_errors: true
  failed_when: false
  chnaged_when: reboot_required.rc != 0
  when: ansible_os_family == "RedHat" 
  notify: "reboot host"

- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers
...
