---

- name: Make sure the PostgreSQL users are present
  become: true
  become_user: "{{ patroni_superuser_username }}"
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    encrypted: true
    login_host: "127.0.0.1"
    login_port: "{{ postgresql_port }}"
    login_user: "{{ patroni_superuser_username }}"
    login_password: "{{ patroni_superuser_password }}"
    login_db: "postgres"
    state: "{{ item.state  | default('present') }}"
  ignore_errors: true
  loop: "{{ postgresql_users | flatten(1) }}"
  loop_control:
    label: "{{ item.name }}"
  when: postgresql_users is defined and postgresql_users | length > 0
  tags: postgresql_users

...
