---

- name: Restart keepalived service
  ansible.builtin.systemd:
    daemon_reload: true
    name: keepalived
    enabled: true
    state: restarted
  listen: "restart keepalived"

- name: Wait for the cluster ip address (VIP) "{{ cluster_vip }}" is running
  ansible.builtin.wait_for:
    host: "{{ cluster_vip }}"
    port: "{{ ansible_ssh_port | default(22) }}"
    state: started
    timeout: 15  # max wait time: 30 seconds
    delay: 2
  ignore_errors: true  # show the error and continue the playbook execution
  listen: "restart keepalived"

...
