---
- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: Set variables for molecule
      set_fact:
        firewall_enabled_at_boot: false
        firewall_enable_ipv6: false # Added to prevent test failures in CI.
        swap_file_create: false # Added to prevent test failures in CI.
        sysctl_set: false # Added to prevent test failures in CI.
        nameservers: ["8.8.8.8", "9.9.9.9"]
        with_haproxy_load_balancing: true
        consul_node_role: server # if dcs_type: "consul"
        consul_bootstrap_expect: true # if dcs_type: "consul"
        cacheable: true

- name: Deploy PostgreSQL Cluster
  import_playbook: ../../deploy_pgcluster.yml
