---

- name: Restart haproxy service
  ansible.builtin.systemd:
    daemon_reload: true
    name: haproxy
    enabled: true
    state: restarted
  listen: "restart haproxy"

- name: Check HAProxy is started and accepting connections
  ansible.builtin.wait_for:
    port: "{{ haproxy_listen_port.stats }}"
    host: "{{ cluster_vip | default(hostvars[inventory_hostname]['inventory_hostname'], true) }}"
    state: started
    timeout: 120
    delay: 10
  ignore_errors: false
  listen: "restart haproxy"

...
