---
- name: Ensure firewalld is present.
  ansible.builtin.package:
    name: firewalld
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3

- name: Configure the firewall service.
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    immediate: true
    permanent: true
    state: enabled
  with_items: "{{ firewall_allowed_tcp_ports }}"

