---

- name: Set timezone to "{{ timezone }}"
  become: true
  become_method: sudo
  community.general.timezone:
    name: "{{ timezone }}"
  when: timezone is defined and timezone | length > 0
  tags: timezone

...
